/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-26 12:46:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Login Page</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css\" integrity=\"sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        *{\r\n");
      out.write("            margin:0;\r\n");
      out.write("            padding:0;\r\n");
      out.write("            box-sizing:border-box;\r\n");
      out.write("            font-family:'Poppins',sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:100vh;\r\n");
      out.write("            background:#f4f5fb;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            overflow:hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .loginPageCard{\r\n");
      out.write("            width:430px;\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:34px;\r\n");
      out.write("            padding:42px;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("            box-shadow:0 20px 40px rgba(0,0,0,0.06);\r\n");
      out.write("            position:relative;\r\n");
      out.write("            overflow:hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageCard::before{\r\n");
      out.write("            content:\"\";\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            top:0;\r\n");
      out.write("            left:0;\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:6px;\r\n");
      out.write("            background:linear-gradient(\r\n");
      out.write("                to right,\r\n");
      out.write("                #675cff,\r\n");
      out.write("                #22d3c5\r\n");
      out.write("            );\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .loginPageHeader{\r\n");
      out.write("            text-align:center;\r\n");
      out.write("            margin-bottom:34px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageLogo{\r\n");
      out.write("            width:80px;\r\n");
      out.write("            height:80px;\r\n");
      out.write("            border-radius:24px;\r\n");
      out.write("            background:linear-gradient(\r\n");
      out.write("                to right,\r\n");
      out.write("                #675cff,\r\n");
      out.write("                #22d3c5\r\n");
      out.write("            );\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            margin:0 auto 20px;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            font-size:32px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            box-shadow:0 12px 24px rgba(103,92,255,0.25);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageTitle{\r\n");
      out.write("            font-size:36px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("            margin-bottom:8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageSubtitle{\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            font-size:15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .loginPageForm{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            flex-direction:column;\r\n");
      out.write("            gap:22px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageInputGroup{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            flex-direction:column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageInputLabel{\r\n");
      out.write("            margin-bottom:10px;\r\n");
      out.write("            font-size:14px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageInputField{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:58px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            outline:none;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            border-radius:16px;\r\n");
      out.write("            padding:0 18px;\r\n");
      out.write("            font-size:16px;\r\n");
      out.write("            border:1px solid #e2e5ef;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageInputField:focus{\r\n");
      out.write("            border-color:#675cff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPagePasswordWrapper{\r\n");
      out.write("            position:relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPagePasswordInput{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:58px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            outline:none;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            border-radius:16px;\r\n");
      out.write("            padding:0 55px 0 18px;\r\n");
      out.write("            font-size:16px;\r\n");
      out.write("            border:1px solid #e2e5ef;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPagePasswordInput:focus{\r\n");
      out.write("            border-color:#675cff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPagePasswordToggle{\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            right:18px;\r\n");
      out.write("            top:50%;\r\n");
      out.write("            transform:translateY(-50%);\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            font-size:20px;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            user-select:none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .loginPageOptions{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            margin-top:-4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageRememberMe{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            gap:8px;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            font-size:14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageForgotPassword{\r\n");
      out.write("            text-decoration:none;\r\n");
      out.write("            color:#675cff;\r\n");
      out.write("            font-size:14px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .loginPageButton{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:58px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:16px;\r\n");
      out.write("            background:linear-gradient(\r\n");
      out.write("                to right,\r\n");
      out.write("                #675cff,\r\n");
      out.write("                #5b4df7\r\n");
      out.write("            );\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            font-size:17px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            transition:0.3s;\r\n");
      out.write("            box-shadow:0 12px 24px rgba(103,92,255,0.25);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageButton:hover{\r\n");
      out.write("            transform:translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageFooter{\r\n");
      out.write("            margin-top:28px;\r\n");
      out.write("            text-align:center;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            font-size:14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loginPageFooter a{\r\n");
      out.write("            color:#675cff;\r\n");
      out.write("            text-decoration:none;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        @media(max-width:500px){\r\n");
      out.write("\r\n");
      out.write("            .loginPageCard{\r\n");
      out.write("                width:92%;\r\n");
      out.write("                padding:30px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .loginPageTitle{\r\n");
      out.write("                font-size:30px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"loginPageCard\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"loginPageHeader\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"loginPageLogo\">\r\n");
      out.write("                <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h1 class=\"loginPageTitle\">\r\n");
      out.write("                Welcome Back\r\n");
      out.write("            </h1>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"loginPageSubtitle\">\r\n");
      out.write("                Login to continue to your dashboard\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form class=\"loginPageForm\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"loginPageInputGroup\">\r\n");
      out.write("\r\n");
      out.write("                <label class=\"loginPageInputLabel\">\r\n");
      out.write("                    EMAIL ADDRESS\r\n");
      out.write("                </label>\r\n");
      out.write("\r\n");
      out.write("                <input \r\n");
      out.write("                    type=\"email\"\r\n");
      out.write("                    placeholder=\"Enter your email\"\r\n");
      out.write("                    class=\"loginPageInputField\"\r\n");
      out.write("                    id=\"loginEmail\"\r\n");
      out.write("                >\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"loginPageInputGroup\">\r\n");
      out.write("\r\n");
      out.write("                <label class=\"loginPageInputLabel\">\r\n");
      out.write("                    PASSWORD\r\n");
      out.write("                </label>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"loginPagePasswordWrapper\">\r\n");
      out.write("\r\n");
      out.write("                    <input \r\n");
      out.write("                        type=\"password\"\r\n");
      out.write("                        placeholder=\"Enter your password\"\r\n");
      out.write("                        class=\"loginPagePasswordInput\"\r\n");
      out.write("                        id=\"loginPassword\"\r\n");
      out.write("                    >\r\n");
      out.write("\r\n");
      out.write("                    <span \r\n");
      out.write("                        class=\"loginPagePasswordToggle\"\r\n");
      out.write("                        id=\"togglePasswordButton\"\r\n");
      out.write("                    >\r\n");
      out.write("                        <i class=\"fa-solid fa-eye\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button \r\n");
      out.write("                type=\"submit\"\r\n");
      out.write("                class=\"loginPageButton\"\r\n");
      out.write("            >\r\n");
      out.write("                Login\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"loginPageFooter\">\r\n");
      out.write("\r\n");
      out.write("            Don't have an account?\r\n");
      out.write("\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                Contact Admin\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"login.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
