/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-20 13:27:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.teacher;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class assignedclass_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Assigned Classes</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        *{\r\n");
      out.write("            margin:0;\r\n");
      out.write("            padding:0;\r\n");
      out.write("            box-sizing:border-box;\r\n");
      out.write("            font-family:'Poppins',sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            background:#f4f5fb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignedClassesContainer{\r\n");
      out.write("            padding:40px 32px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignedClassesHeading{\r\n");
      out.write("            font-size:44px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignedClassesSubtitle{\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            margin-top:4px;\r\n");
      out.write("            margin-bottom:30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignedClassesGrid{\r\n");
      out.write("            display:grid;\r\n");
      out.write("            grid-template-columns:repeat(auto-fit,minmax(320px,1fr));\r\n");
      out.write("            gap:20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignedClassesCard{\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:28px;\r\n");
      out.write("            padding:28px;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("            position:relative;\r\n");
      out.write("            overflow:hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignedClassesCard::before{\r\n");
      out.write("            content:\"\";\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            top:0;\r\n");
      out.write("            left:0;\r\n");
      out.write("            width:5px;\r\n");
      out.write("            height:100%;\r\n");
      out.write("            background:#675cff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignedClassesBadge{\r\n");
      out.write("            display:inline-block;\r\n");
      out.write("            padding:8px 16px;\r\n");
      out.write("            border-radius:30px;\r\n");
      out.write("            background:#ecebff;\r\n");
      out.write("            color:#675cff;\r\n");
      out.write("            font-size:14px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            margin-bottom:20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignedClassesTitle{\r\n");
      out.write("            font-size:28px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("            margin-bottom:6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignedClassesSubject{\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            margin-bottom:24px;\r\n");
      out.write("            font-size:17px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignedClassesInfo{\r\n");
      out.write("            margin-bottom:12px;\r\n");
      out.write("            color:#475467;\r\n");
      out.write("            font-size:16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"assignedClassesContainer\">\r\n");
      out.write("\r\n");
      out.write("        <h1 class=\"assignedClassesHeading\">\r\n");
      out.write("            Assigned Classes\r\n");
      out.write("        </h1>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"assignedClassesSubtitle\">\r\n");
      out.write("            Classes and subjects assigned to you\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"assignedClassesGrid\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"assignedClassesCard\">\r\n");
      out.write("\r\n");
      out.write("                <span class=\"assignedClassesBadge\">\r\n");
      out.write("                    Science\r\n");
      out.write("                </span>\r\n");
      out.write("\r\n");
      out.write("                <h2 class=\"assignedClassesTitle\">\r\n");
      out.write("                    Class 8\r\n");
      out.write("                </h2>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"assignedClassesSubject\">\r\n");
      out.write("                    Subject: Science\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"assignedClassesInfo\">\r\n");
      out.write("                    ð¨âð Students: 32\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"assignedClassesInfo\">\r\n");
      out.write("                    ð Timing: 9:00 AM\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"assignedClassesInfo\">\r\n");
      out.write("                    ð Room: 204\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"assignedClassesCard\">\r\n");
      out.write("\r\n");
      out.write("                <span class=\"assignedClassesBadge\">\r\n");
      out.write("                    Physics\r\n");
      out.write("                </span>\r\n");
      out.write("\r\n");
      out.write("                <h2 class=\"assignedClassesTitle\">\r\n");
      out.write("                    Class 9\r\n");
      out.write("                </h2>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"assignedClassesSubject\">\r\n");
      out.write("                    Subject: Physics\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"assignedClassesInfo\">\r\n");
      out.write("                    ð¨âð Students: 28\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"assignedClassesInfo\">\r\n");
      out.write("                    ð Timing: 11:00 AM\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"assignedClassesInfo\">\r\n");
      out.write("                    ð Room: 301\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
