/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-30 09:13:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.teacher;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class attendance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Mark Attendance</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        *{\r\n");
      out.write("            margin:0;\r\n");
      out.write("            padding:0;\r\n");
      out.write("            box-sizing:border-box;\r\n");
      out.write("            font-family:'Poppins',sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            background:#f4f5fb;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: start;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           TOPBAR\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceTopbar{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            padding:12px 28px;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            border-bottom:1px solid #e7e7e7;\r\n");
      out.write("            border-radius: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceTopbarTitle{\r\n");
      out.write("            font-size:20px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceTeacherProfile{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            gap:12px;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            padding:10px 14px;\r\n");
      out.write("            border-radius:16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceTeacherAvatar{\r\n");
      out.write("            width:42px;\r\n");
      out.write("            height:42px;\r\n");
      out.write("            border-radius:50%;\r\n");
      out.write("            background:linear-gradient(to right,#675cff,#1dd5c8);\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceTeacherRole{\r\n");
      out.write("            font-size:13px;\r\n");
      out.write("            color:#8c8c8c;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           PAGE CONTAINER\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendancePageContainer{\r\n");
      out.write("            padding:5px 10px;\r\n");
      out.write("            width: 82%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceMainHeading{\r\n");
      out.write("            font-size:44px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceSubtitle{\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            margin-top:4px;\r\n");
      out.write("            margin-bottom:30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           OVERVIEW CARDS\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceOverviewGrid{\r\n");
      out.write("            display:grid;\r\n");
      out.write("            grid-template-columns:repeat(auto-fit,minmax(250px,1fr));\r\n");
      out.write("            gap:20px;\r\n");
      out.write("            margin-bottom:10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceOverviewCard{\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:28px;\r\n");
      out.write("            padding:15px;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceCardLabel{\r\n");
      out.write("            font-size:15px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            margin-bottom:0px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceCardValue{\r\n");
      out.write("            font-size:42px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePresentText{\r\n");
      out.write("            color:#00c896;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAbsentText{\r\n");
      out.write("            color:#ff5a5f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePercentageText{\r\n");
      out.write("            color:#675cff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           FILTER SECTION\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceFilterCard{\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:30px;\r\n");
      out.write("            padding:20px;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("            margin-bottom:20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceFilterGrid{\r\n");
      out.write("            display:grid;\r\n");
      out.write("            grid-template-columns:1fr 1fr;\r\n");
      out.write("            gap:20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceFormGroup{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            flex-direction:column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceFormLabel{\r\n");
      out.write("            margin-bottom:10px;\r\n");
      out.write("            font-size:14px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceInputField,\r\n");
      out.write("        .attendanceSelectField{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:54px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            outline:none;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            border-radius:14px;\r\n");
      out.write("            padding:0 18px;\r\n");
      out.write("            font-size:16px;\r\n");
      out.write("            border:1px solid #e2e5ef;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           TABLE\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceTableCard{\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:30px;\r\n");
      out.write("            overflow-y: scroll;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("            height: 380px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceTable{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            border-collapse:collapse;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceTable thead{\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceTable th{\r\n");
      out.write("            text-align:left;\r\n");
      out.write("            padding:10px 20px;\r\n");
      out.write("            font-size:13px;\r\n");
      out.write("            color:#98a2b3;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceTable td{\r\n");
      out.write("            padding:15px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            border-top:1px solid #ececec;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceStudentName{\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           STATUS BUTTONS\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceActionButtons{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            gap:10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePresentButton,\r\n");
      out.write("        .attendanceAbsentButton{\r\n");
      out.write("            border:none;\r\n");
      out.write("            padding:10px 16px;\r\n");
      out.write("            border-radius:12px;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            transition:0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePresentButton{\r\n");
      out.write("            background:#dcfff6;\r\n");
      out.write("            color:#00c896;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAbsentButton{\r\n");
      out.write("            background:#ffe3e3;\r\n");
      out.write("            color:#ff5a5f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePresentButton.active{\r\n");
      out.write("            background:#00c896;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAbsentButton.active{\r\n");
      out.write("            background:#ff5a5f;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           SAVE BUTTON\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceSaveContainer{\r\n");
      out.write("            margin-top:5px;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:flex-end;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceSaveButton{\r\n");
      out.write("            border:none;\r\n");
      out.write("            background:#5c4ef7;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            padding:14px 28px;\r\n");
      out.write("            border-radius:14px;\r\n");
      out.write("            font-size:16px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            box-shadow:0 10px 20px rgba(92,78,247,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media(max-width:900px){\r\n");
      out.write("\r\n");
      out.write("            .attendanceFilterGrid{\r\n");
      out.write("                grid-template-columns:1fr;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .attendanceTable{\r\n");
      out.write("                display:block;\r\n");
      out.write("                overflow-x:auto;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .attendanceFilterSection{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    gap:20px;\r\n");
      out.write("    margin-bottom:24px;\r\n");
      out.write("    background:#ffffff;\r\n");
      out.write("    padding:24px;\r\n");
      out.write("    border-radius:24px;\r\n");
      out.write("    border:1px solid #ececec;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attendanceFilterInput{\r\n");
      out.write("    flex:1;\r\n");
      out.write("    height:56px;\r\n");
      out.write("    border:none;\r\n");
      out.write("    outline:none;\r\n");
      out.write("    background:#f5f6fb;\r\n");
      out.write("    border-radius:16px;\r\n");
      out.write("    padding:0 18px;\r\n");
      out.write("    font-size:16px;\r\n");
      out.write("    font-weight:500;\r\n");
      out.write("    color:#111827;\r\n");
      out.write("    border:1px solid #e2e5ef;\r\n");
      out.write("    transition:0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attendanceFilterInput:focus{\r\n");
      out.write("    border-color:#675cff;\r\n");
      out.write("    box-shadow:0 0 0 4px rgba(103,92,255,0.12);\r\n");
      out.write("    background:#ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attendanceFilterInput::placeholder{\r\n");
      out.write("    color:#98a2b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- PAGE -->\r\n");
      out.write("    <div class=\"attendancePageContainer\">\r\n");
      out.write("    <div class=\"attendanceTopbar\">\r\n");
      out.write("        <h2 class=\"attendanceTopbarTitle\"> Mark Attendance </h2>\r\n");
      out.write("        <div class=\"attendanceTeacherProfile\">\r\n");
      out.write("            <div class=\"attendanceTeacherAvatar\"> T </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <h4>Teacher</h4>\r\n");
      out.write("                <p class=\"attendanceTeacherRole\"> Science Department </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("        <h1 class=\"attendanceMainHeading\">  Attendance Management </h1>\r\n");
      out.write("        <p class=\"attendanceSubtitle\"> Mark daily attendance for students </p>\r\n");
      out.write("        <!-- OVERVIEW -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"attendanceOverviewGrid\">\r\n");
      out.write("            <div class=\"attendanceOverviewCard\">\r\n");
      out.write("                <p class=\"attendanceCardLabel\"> TOTAL STUDENTS </p>\r\n");
      out.write("                <h2 class=\"attendanceCardValue\" id=\"totalStudents\"> 0 </h2>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"attendanceOverviewCard\">\r\n");
      out.write("                <p class=\"attendanceCardLabel\"> PRESENT </p>\r\n");
      out.write("                <h2 class=\"attendanceCardValue attendancePresentText\" id=\"presentCount\"> 0 </h2>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"attendanceOverviewCard\">\r\n");
      out.write("                <p class=\"attendanceCardLabel\"> ABSENT</p>\r\n");
      out.write("                <h2 class=\"attendanceCardValue attendanceAbsentText\" id=\"absentCount\"> 0</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- =========================\r\n");
      out.write("     DATE + CLASS INPUTS\r\n");
      out.write("========================= -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"attendanceFilterSection\">\r\n");
      out.write("    <input type=\"date\"id=\"attendanceDate\" class=\"attendanceFilterInput\">\r\n");
      out.write("    <select id=\"classId\" class=\"attendanceFilterInput\">\r\n");
      out.write("\r\n");
      out.write("    <option value=\"\">Select Class</option>\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- =========================\r\n");
      out.write("     TABLE\r\n");
      out.write("========================= -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"attendanceTableCard\">\r\n");
      out.write("    <table class=\"attendanceTable\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>ROLL NO</th>\r\n");
      out.write("                <th>FIRST NAME</th>\r\n");
      out.write("                <th>MIDDLE NAME</th>\r\n");
      out.write("                <th>LAST NAME</th>\r\n");
      out.write("                <th>GENDER</th>\r\n");
      out.write("                <th>STATUS</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody id=\"attendanceTableBody\">\r\n");
      out.write("            <!-- ROW 1 -->\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"6\" style=\"text-align: center; padding: 20px; color: #888; font-size: 1.2rem;\">Select Class</td>            </tr>\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- SAVE BUTTON -->\r\n");
      out.write("<div class=\"attendanceSaveContainer\">\r\n");
      out.write("    <button class=\"attendanceSaveButton\"id=\"saveAttendanceButton\">Save Attendance</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"attendance.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!-- TABLE\r\n");
      out.write("        <div class=\"attendanceTableCard\">\r\n");
      out.write("            <table class=\"attendanceTable\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>ROLL NO</th>\r\n");
      out.write("                        <th>FIRST NAME</th>\r\n");
      out.write("                        <th>MIDDLE NAME</th>\r\n");
      out.write("                        <th>LAST NAME</th>\r\n");
      out.write("                        <th>GENDER</th>\r\n");
      out.write("                        <th>STATUS</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>101</td>\r\n");
      out.write("                        <td class=\"attendanceStudentName\">Aarav</td>\r\n");
      out.write("                        <td>Kumar</td>\r\n");
      out.write("                        <td>R</td>\r\n");
      out.write("                        <td>Male</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div class=\"attendanceActionButtons\">\r\n");
      out.write("                                <button class=\"attendancePresentButton\"> Present </button>\r\n");
      out.write("                                <button class=\"attendanceAbsentButton\"> Absent </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>102</td>\r\n");
      out.write("                        <td class=\"attendanceStudentName\">Diya</td>\r\n");
      out.write("                        <td>Patel</td>\r\n");
      out.write("                        <td>S</td>\r\n");
      out.write("                        <td>Female</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div class=\"attendanceActionButtons\">\r\n");
      out.write("                                <button class=\"attendancePresentButton\"> Present</button>\r\n");
      out.write("                                <button class=\"attendanceAbsentButton\"> Absent </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>103</td>\r\n");
      out.write("                        <td class=\"attendanceStudentName\">Rohan</td>\r\n");
      out.write("                        <td>Singh</td>\r\n");
      out.write("                        <td>K</td>\r\n");
      out.write("                        <td>Male</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div class=\"attendanceActionButtons\">\r\n");
      out.write("                                <button class=\"attendancePresentButton\"> Present  </button>\r\n");
      out.write("                                <button class=\"attendanceAbsentButton\"> Absent </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>104</td>\r\n");
      out.write("                        <td class=\"attendanceStudentName\">Sneha</td>\r\n");
      out.write("                        <td>Gupta</td>\r\n");
      out.write("                        <td>P</td>\r\n");
      out.write("                        <td>Female</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div class=\"attendanceActionButtons\">\r\n");
      out.write("                                <button class=\"attendancePresentButton\"> Present </button>\r\n");
      out.write("                                <button class=\"attendanceAbsentButton\"> Absent</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"attendanceSaveContainer\">\r\n");
      out.write("            <button class=\"attendanceSaveButton\"> Save Attendance </button>\r\n");
      out.write("        </div> -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
