/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-22 04:37:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.student;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Student Profile</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        *{\r\n");
      out.write("            margin:0;\r\n");
      out.write("            padding:0;\r\n");
      out.write("            box-sizing:border-box;\r\n");
      out.write("            font-family:'Poppins',sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            background:#f4f5fb;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: start;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileContainer{\r\n");
      out.write("            padding:10px 10px;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileHeading{\r\n");
      out.write("            font-size:44px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileSubtitle{\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            margin-top:4px;\r\n");
      out.write("            margin-bottom:30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileCard{\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:32px;\r\n");
      out.write("            padding:40px;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            gap:40px;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileImageSection{\r\n");
      out.write("            text-align:center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileAvatar{\r\n");
      out.write("            width:140px;\r\n");
      out.write("            height:140px;\r\n");
      out.write("            border-radius:50%;\r\n");
      out.write("            background:linear-gradient(to right,#675cff,#1dd5c8);\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("            font-size:52px;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            margin-bottom:18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileBadge{\r\n");
      out.write("            display:inline-block;\r\n");
      out.write("            padding:8px 16px;\r\n");
      out.write("            border-radius:30px;\r\n");
      out.write("            background:#dcfff6;\r\n");
      out.write("            color:#00c896;\r\n");
      out.write("            font-size:14px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileDetails{\r\n");
      out.write("            flex:1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileName{\r\n");
      out.write("            font-size:34px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("            margin-bottom:8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileClass{\r\n");
      out.write("            color:#675cff;\r\n");
      out.write("            font-size:18px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            margin-bottom:30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileGrid{\r\n");
      out.write("            display:grid;\r\n");
      out.write("            grid-template-columns:1fr 1fr;\r\n");
      out.write("            gap:24px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileInfoCard{\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            border-radius:20px;\r\n");
      out.write("            padding:20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileInfoLabel{\r\n");
      out.write("            font-size:13px;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            margin-bottom:8px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .studentProfileInfoValue{\r\n");
      out.write("            font-size:18px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"studentProfileContainer\">\r\n");
      out.write("\r\n");
      out.write("        <h1 class=\"studentProfileHeading\">\r\n");
      out.write("            My Profile\r\n");
      out.write("        </h1>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"studentProfileSubtitle\">\r\n");
      out.write("            View personal and academic information\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"studentProfileCard\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"studentProfileImageSection\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"studentProfileAvatar\">\r\n");
      out.write("                    A\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <span class=\"studentProfileBadge\">\r\n");
      out.write("                    Active Student\r\n");
      out.write("                </span>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"studentProfileDetails\">\r\n");
      out.write("\r\n");
      out.write("                <h2 class=\"studentProfileName\">\r\n");
      out.write("                    Aarav Kumar\r\n");
      out.write("                </h2>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"studentProfileClass\">\r\n");
      out.write("                    Class 8 - Science\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"studentProfileGrid\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"studentProfileInfoCard\">\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"studentProfileInfoLabel\">\r\n");
      out.write("                            ROLL NUMBER\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <h3 class=\"studentProfileInfoValue\">\r\n");
      out.write("                            101\r\n");
      out.write("                        </h3>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"studentProfileInfoCard\">\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"studentProfileInfoLabel\">\r\n");
      out.write("                            EMAIL\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <h3 class=\"studentProfileInfoValue\">\r\n");
      out.write("                            aarav@gmail.com\r\n");
      out.write("                        </h3>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"studentProfileInfoCard\">\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"studentProfileInfoLabel\">\r\n");
      out.write("                            PHONE\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <h3 class=\"studentProfileInfoValue\">\r\n");
      out.write("                            9876543210\r\n");
      out.write("                        </h3>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"studentProfileInfoCard\">\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"studentProfileInfoLabel\">\r\n");
      out.write("                            PARENT NAME\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <h3 class=\"studentProfileInfoValue\">\r\n");
      out.write("                            Mr. Kumar\r\n");
      out.write("                        </h3>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"studentProfileInfoCard\">\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"studentProfileInfoLabel\">\r\n");
      out.write("                            DATE OF BIRTH\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <h3 class=\"studentProfileInfoValue\">\r\n");
      out.write("                            12 Aug 2008\r\n");
      out.write("                        </h3>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"studentProfileInfoCard\">\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"studentProfileInfoLabel\">\r\n");
      out.write("                            ADDRESS\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <h3 class=\"studentProfileInfoValue\">\r\n");
      out.write("                            Bangalore, India\r\n");
      out.write("                        </h3>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
