/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-20 09:15:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class attendance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Attendance UI</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        *{\r\n");
      out.write("            margin:0;\r\n");
      out.write("            padding:0;\r\n");
      out.write("            box-sizing:border-box;\r\n");
      out.write("            font-family:'Poppins',sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            background:#f4f5fb;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: start;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           TOPBAR\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceTopbar{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            padding:12px 28px;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            border-bottom:1px solid #e7e7e7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceTopbarTitle{\r\n");
      out.write("            font-size:20px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAdminProfile{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            gap:12px;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            padding:10px 14px;\r\n");
      out.write("            border-radius:16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAdminAvatar{\r\n");
      out.write("            width:42px;\r\n");
      out.write("            height:42px;\r\n");
      out.write("            border-radius:50%;\r\n");
      out.write("            background:linear-gradient(to right,#675cff,#1dd5c8);\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAdminRole{\r\n");
      out.write("            font-size:13px;\r\n");
      out.write("            color:#8c8c8c;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           PAGE CONTAINER\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendancePageContainer{\r\n");
      out.write("            padding:10px 32px;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePageHeader{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            margin-bottom:30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePageHeading{\r\n");
      out.write("            font-size:40px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePageSubtitle{\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            margin-top:4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           REFRESH BUTTON\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceRefreshButton{\r\n");
      out.write("            border:none;\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            padding:14px 28px;\r\n");
      out.write("            border-radius:14px;\r\n");
      out.write("            font-size:18px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            border:1px solid #e2e5ef;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            transition:0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceRefreshButton:hover{\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           STATS GRID\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceStatsGrid{\r\n");
      out.write("            display:grid;\r\n");
      out.write("            grid-template-columns:repeat(auto-fit,minmax(260px,1fr));\r\n");
      out.write("            gap:20px;\r\n");
      out.write("            margin-bottom:32px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           STAT CARD\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceStatCard{\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:28px;\r\n");
      out.write("            padding:14px;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            gap:18px;\r\n");
      out.write("            position:relative;\r\n");
      out.write("            overflow:hidden;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceStatCard::before{\r\n");
      out.write("            content:\"\";\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            left:0;\r\n");
      out.write("            top:0;\r\n");
      out.write("            width:5px;\r\n");
      out.write("            height:100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePresentCard::before{\r\n");
      out.write("            background:#00d09c;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAbsentCard::before{\r\n");
      out.write("            background:#ff5a5f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceLateCard::before{\r\n");
      out.write("            background:#ffae00;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAverageCard::before{\r\n");
      out.write("            background:#675cff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           ICON BOX\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceIconBox{\r\n");
      out.write("            width:60px;\r\n");
      out.write("            height:60px;\r\n");
      out.write("            border-radius:16px;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("            font-size:24px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePresentIcon{\r\n");
      out.write("            background:#dcfff6;\r\n");
      out.write("            color:#00c896;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAbsentIcon{\r\n");
      out.write("            background:#ffe3e3;\r\n");
      out.write("            color:#ff5a5f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceLateIcon{\r\n");
      out.write("            background:#fff2db;\r\n");
      out.write("            color:#ff9800;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAverageIcon{\r\n");
      out.write("            background:#ecebff;\r\n");
      out.write("            color:#675cff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           STAT TEXT\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceStatLabel{\r\n");
      out.write("            font-size:15px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            margin-bottom:6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceStatNumber{\r\n");
      out.write("            font-size:36px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            line-height:1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           TABLE CARD\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceTableCard{\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:30px;\r\n");
      out.write("            overflow-y:scroll;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           TABLE\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceDataTable{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            border-collapse:collapse;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceDataTable thead{\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceDataTable th{\r\n");
      out.write("            text-align:left;\r\n");
      out.write("            padding:10px 22px;\r\n");
      out.write("            font-size:13px;\r\n");
      out.write("            color:#98a2b3;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceDataTable td{\r\n");
      out.write("            padding:12px;\r\n");
      out.write("            border-top:1px solid #ececec;\r\n");
      out.write("            font-size:16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceStudentName{\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           STATUS BADGES\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .attendanceStatusBadge{\r\n");
      out.write("            display:inline-block;\r\n");
      out.write("            padding:7px 14px;\r\n");
      out.write("            border-radius:30px;\r\n");
      out.write("            font-size:14px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendancePresentBadge{\r\n");
      out.write("            background:#dcfff6;\r\n");
      out.write("            color:#00c896;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceAbsentBadge{\r\n");
      out.write("            background:#ffe3e3;\r\n");
      out.write("            color:#ff5a5f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .attendanceLateBadge{\r\n");
      out.write("            background:#fff2db;\r\n");
      out.write("            color:#ff9800;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           RESPONSIVE\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        @media(max-width:768px){\r\n");
      out.write("\r\n");
      out.write("            .attendancePageHeader{\r\n");
      out.write("                flex-direction:column;\r\n");
      out.write("                align-items:flex-start;\r\n");
      out.write("                gap:20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .attendanceDataTable{\r\n");
      out.write("                display:block;\r\n");
      out.write("                overflow-x:auto;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- =========================\r\n");
      out.write("         TOPBAR\r\n");
      out.write("    ========================== -->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- =========================\r\n");
      out.write("         PAGE CONTENT\r\n");
      out.write("    ========================== -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"attendancePageContainer\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"attendanceTopbar\">\r\n");
      out.write("\r\n");
      out.write("        <h2 class=\"attendanceTopbarTitle\">\r\n");
      out.write("            Attendance\r\n");
      out.write("        </h2>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"attendanceAdminProfile\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"attendanceAdminAvatar\">\r\n");
      out.write("                A\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("\r\n");
      out.write("                <h4>Admin</h4>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"attendanceAdminRole\">\r\n");
      out.write("                    Super Admin\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- HEADER -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"attendancePageHeader\">\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("\r\n");
      out.write("                <h1 class=\"attendancePageHeading\">\r\n");
      out.write("                    Attendance\r\n");
      out.write("                </h1>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"attendancePageSubtitle\">\r\n");
      out.write("                    Daily attendance overview\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"attendanceRefreshButton\">\r\n");
      out.write("                â» Refresh\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- STATS -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"attendanceStatsGrid\">\r\n");
      out.write("\r\n");
      out.write("            <!-- PRESENT -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"attendanceStatCard attendancePresentCard\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"attendanceIconBox attendancePresentIcon\">\r\n");
      out.write("                    â\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"attendanceStatLabel\">\r\n");
      out.write("                        PRESENT\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"attendanceStatNumber\">\r\n");
      out.write("                        5\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ABSENT -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"attendanceStatCard attendanceAbsentCard\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"attendanceIconBox attendanceAbsentIcon\">\r\n");
      out.write("                    â\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"attendanceStatLabel\">\r\n");
      out.write("                        ABSENT\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"attendanceStatNumber\">\r\n");
      out.write("                        2\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- LATE -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"attendanceStatCard attendanceLateCard\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"attendanceIconBox attendanceLateIcon\">\r\n");
      out.write("                    â°\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"attendanceStatLabel\">\r\n");
      out.write("                        LATE\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"attendanceStatNumber\">\r\n");
      out.write("                        1\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- AVG RATE -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"attendanceStatCard attendanceAverageCard\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"attendanceIconBox attendanceAverageIcon\">\r\n");
      out.write("                    %\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"attendanceStatLabel\">\r\n");
      out.write("                        AVG RATE\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"attendanceStatNumber\">\r\n");
      out.write("                        63%\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- TABLE -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"attendanceTableCard\">\r\n");
      out.write("\r\n");
      out.write("            <table class=\"attendanceDataTable\">\r\n");
      out.write("\r\n");
      out.write("                <thead>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <th>STUDENT</th>\r\n");
      out.write("                        <th>CLASS</th>\r\n");
      out.write("                        <th>DATE</th>\r\n");
      out.write("                        <th>STATUS</th>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                </thead>\r\n");
      out.write("\r\n");
      out.write("                <tbody>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <td class=\"attendanceStudentName\">\r\n");
      out.write("                            Aarav Kumar\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Grade 10-A\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            2024-11-18\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"attendanceStatusBadge attendancePresentBadge\">\r\n");
      out.write("                                Present\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <td class=\"attendanceStudentName\">\r\n");
      out.write("                            Diya Patel\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Grade 10-A\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            2024-11-18\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"attendanceStatusBadge attendancePresentBadge\">\r\n");
      out.write("                                Present\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <td class=\"attendanceStudentName\">\r\n");
      out.write("                            Rohan Singh\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Grade 10-B\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            2024-11-18\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"attendanceStatusBadge attendanceAbsentBadge\">\r\n");
      out.write("                                Absent\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <td class=\"attendanceStudentName\">\r\n");
      out.write("                            Sneha Gupta\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Grade 10-A\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            2024-11-18\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"attendanceStatusBadge attendancePresentBadge\">\r\n");
      out.write("                                Present\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <td class=\"attendanceStudentName\">\r\n");
      out.write("                            Aarav Kumar\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Grade 10-A\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            2024-11-19\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"attendanceStatusBadge attendanceAbsentBadge\">\r\n");
      out.write("                                Absent\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <td class=\"attendanceStudentName\">\r\n");
      out.write("                            Diya Patel\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Grade 10-A\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            2024-11-19\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"attendanceStatusBadge attendancePresentBadge\">\r\n");
      out.write("                                Present\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <td class=\"attendanceStudentName\">\r\n");
      out.write("                            Rohan Singh\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Grade 10-B\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            2024-11-19\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"attendanceStatusBadge attendancePresentBadge\">\r\n");
      out.write("                                Present\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <td class=\"attendanceStudentName\">\r\n");
      out.write("                            Sneha Gupta\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            Grade 10-A\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            2024-11-19\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"attendanceStatusBadge attendanceLateBadge\">\r\n");
      out.write("                                Late\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
