/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-20 10:01:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  <title>School Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    *{\r\n");
      out.write("      margin:0;\r\n");
      out.write("      padding:0;\r\n");
      out.write("      box-sizing:border-box;\r\n");
      out.write("      font-family:'Poppins',sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body{\r\n");
      out.write("      background:#f3f4f8;\r\n");
      out.write("      display:flex;\r\n");
      out.write("      min-height:100vh;\r\n");
      out.write("      color:#1b1b1b;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* SIDEBAR */\r\n");
      out.write("\r\n");
      out.write("    .sidebar{\r\n");
      out.write("      width:280px;\r\n");
      out.write("      background:#11162d;\r\n");
      out.write("      color:#fff;\r\n");
      out.write("      padding:20px 14px;\r\n");
      out.write("      display:flex;\r\n");
      out.write("      flex-direction:column;\r\n");
      out.write("      justify-content:space-between;\r\n");
      out.write("      border-top-right-radius:20px;\r\n");
      out.write("      border-bottom-right-radius:20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo{\r\n");
      out.write("      width:42px;\r\n");
      out.write("      height:42px;\r\n");
      out.write("      border-radius:12px;\r\n");
      out.write("      background:#2a2f55;\r\n");
      out.write("      display:flex;\r\n");
      out.write("      align-items:center;\r\n");
      out.write("      justify-content:center;\r\n");
      out.write("      color:#7b6dff;\r\n");
      out.write("      font-size:22px;\r\n");
      out.write("      margin-bottom:35px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu-title{\r\n");
      out.write("      font-size:12px;\r\n");
      out.write("      color:#9ba1c4;\r\n");
      out.write("      margin:20px 10px 10px;\r\n");
      out.write("      letter-spacing:1px;\r\n");
      out.write("      font-weight:600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu{\r\n");
      out.write("      list-style:none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu li{\r\n");
      out.write("      padding:14px 16px;\r\n");
      out.write("      border-radius:12px;\r\n");
      out.write("      margin-bottom:8px;\r\n");
      out.write("      cursor:pointer;\r\n");
      out.write("      display:flex;\r\n");
      out.write("      align-items:center;\r\n");
      out.write("      gap:14px;\r\n");
      out.write("      color:#aeb4d1;\r\n");
      out.write("      transition:0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu li:hover{\r\n");
      out.write("      background:#242b4d;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu li.active{\r\n");
      out.write("      background:#4b42c7;\r\n");
      out.write("      color:#fff;\r\n");
      out.write("      font-weight:500;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .bottom-menu{\r\n");
      out.write("      margin-top:40px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* MAIN CONTENT */\r\n");
      out.write("\r\n");
      out.write("    .main{\r\n");
      out.write("      flex:1;\r\n");
      out.write("      padding:10px 12px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .topbar{\r\n");
      out.write("      background:#fff;\r\n");
      out.write("      border-radius:18px;\r\n");
      out.write("      padding:10px 25px;\r\n");
      out.write("      display:flex;\r\n");
      out.write("      justify-content:space-between;\r\n");
      out.write("      align-items:center;\r\n");
      out.write("      box-shadow:0 2px 10px rgba(0,0,0,0.03);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .topbar h2{\r\n");
      out.write("      font-size:20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile{\r\n");
      out.write("      display:flex;\r\n");
      out.write("      align-items:center;\r\n");
      out.write("      gap:12px;\r\n");
      out.write("      background:#f5f6fb;\r\n");
      out.write("      padding:10px 16px;\r\n");
      out.write("      border-radius:16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .avatar{\r\n");
      out.write("      width:42px;\r\n");
      out.write("      height:42px;\r\n");
      out.write("      border-radius:50%;\r\n");
      out.write("      background:linear-gradient(to right,#4b42c7,#39d2b4);\r\n");
      out.write("      display:flex;\r\n");
      out.write("      align-items:center;\r\n");
      out.write("      justify-content:center;\r\n");
      out.write("      color:#fff;\r\n");
      out.write("      font-weight:600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile small{\r\n");
      out.write("      color:#7c7c7c;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-title{\r\n");
      out.write("      margin:35px 0 20px;\r\n");
      out.write("      font-size:34px;\r\n");
      out.write("      font-weight:700;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stats{\r\n");
      out.write("      display:grid;\r\n");
      out.write("      grid-template-columns:repeat(auto-fit,minmax(240px,1fr));\r\n");
      out.write("      gap:20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card{\r\n");
      out.write("      background:#fff;\r\n");
      out.write("      border-radius:24px;\r\n");
      out.write("      padding:20px;\r\n");
      out.write("      display:flex;\r\n");
      out.write("      align-items:center;\r\n");
      out.write("      gap:18px;\r\n");
      out.write("      position:relative;\r\n");
      out.write("      overflow:hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card::before{\r\n");
      out.write("      content:\"\";\r\n");
      out.write("      position:absolute;\r\n");
      out.write("      left:0;\r\n");
      out.write("      top:0;\r\n");
      out.write("      width:6px;\r\n");
      out.write("      height:100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card.purple::before{ background:#6c63ff; }\r\n");
      out.write("    .card.green::before{ background:#27d6b5; }\r\n");
      out.write("    .card.orange::before{ background:#ffb347; }\r\n");
      out.write("    .card.red::before{ background:#ff6b6b; }\r\n");
      out.write("\r\n");
      out.write("    .icon-box{\r\n");
      out.write("      width:58px;\r\n");
      out.write("      height:58px;\r\n");
      out.write("      border-radius:16px;\r\n");
      out.write("      display:flex;\r\n");
      out.write("      align-items:center;\r\n");
      out.write("      justify-content:center;\r\n");
      out.write("      font-size:24px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .purple .icon-box{ background:#ecebff; color:#6c63ff; }\r\n");
      out.write("    .green .icon-box{ background:#dff8f4; color:#27d6b5; }\r\n");
      out.write("    .orange .icon-box{ background:#fff2dd; color:#ffb347; }\r\n");
      out.write("    .red .icon-box{ background:#ffe7e7; color:#ff6b6b; }\r\n");
      out.write("\r\n");
      out.write("    .card h4{\r\n");
      out.write("      font-size:14px;\r\n");
      out.write("      color:#7a7a7a;\r\n");
      out.write("      margin-bottom:6px;\r\n");
      out.write("      font-weight:600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card h1{\r\n");
      out.write("      font-size:35px;\r\n");
      out.write("      line-height:1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* TABLES */\r\n");
      out.write("\r\n");
      out.write("    .table-wrapper{\r\n");
      out.write("      margin-top:28px;\r\n");
      out.write("      display:grid;\r\n");
      out.write("      grid-template-columns:1fr 1fr;\r\n");
      out.write("      gap:24px;\r\n");
      out.write("      height: 430px;\r\n");
      out.write("      overflow-y: scroll;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table-card{\r\n");
      out.write("      background:#fff;\r\n");
      out.write("      border-radius:24px;\r\n");
      out.write("      padding:20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table-card h3{\r\n");
      out.write("      margin-bottom:20px;\r\n");
      out.write("      font-size:24px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table{\r\n");
      out.write("      width:100%;\r\n");
      out.write("      border-collapse:collapse;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    th{\r\n");
      out.write("      text-align:left;\r\n");
      out.write("      font-size:13px;\r\n");
      out.write("      color:#8b8b8b;\r\n");
      out.write("      padding:14px;\r\n");
      out.write("      background:#f3f4f8;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    td{\r\n");
      out.write("      padding:12px 14px;\r\n");
      out.write("      border-bottom:1px solid #eee;\r\n");
      out.write("      font-size:15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    tr:last-child td{\r\n");
      out.write("      border-bottom:none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .badge{\r\n");
      out.write("      padding:6px 14px;\r\n");
      out.write("      border-radius:20px;\r\n");
      out.write("      font-size:12px;\r\n");
      out.write("      font-weight:600;\r\n");
      out.write("      display:inline-block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .active-badge{\r\n");
      out.write("      background:#dff8f4;\r\n");
      out.write("      color:#19b899;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .enrolled-badge{\r\n");
      out.write("      background:#ecebff;\r\n");
      out.write("      color:#6c63ff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* RESPONSIVE */\r\n");
      out.write("\r\n");
      out.write("    @media(max-width:1000px){\r\n");
      out.write("      .table-wrapper{\r\n");
      out.write("        grid-template-columns:1fr;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media(max-width:768px){\r\n");
      out.write("      body{\r\n");
      out.write("        flex-direction:column;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .sidebar{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        border-radius:0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .main{\r\n");
      out.write("        padding:15px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .topbar{\r\n");
      out.write("        flex-direction:column;\r\n");
      out.write("        gap:15px;\r\n");
      out.write("        align-items:flex-start;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- SIDEBAR -->\r\n");
      out.write("\r\n");
      out.write("  <!--   <div class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("      <div class=\"logo\"></div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"menu-title\">MAIN</div>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"menu\">\r\n");
      out.write("        <li class=\"active\">Dashboard</li>\r\n");
      out.write("        <li>Teachers</li>\r\n");
      out.write("        <li>Students</li>\r\n");
      out.write("        <li>Classes</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"menu-title\">ASSIGNMENTS</div>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"menu\">\r\n");
      out.write("        <li>Assign Students</li>\r\n");
      out.write("        <li>Assign Teachers</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"menu-title\">ACADEMICS</div>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"menu\">\r\n");
      out.write("        <li>Attendance</li>\r\n");
      out.write("        <li>Results</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"bottom-menu\">\r\n");
      out.write("      <ul class=\"menu\">\r\n");
      out.write("        <li>Logout</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div> -->\r\n");
      out.write("  \r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- MAIN -->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"topbar\">\r\n");
      out.write("      <h2>Dashboard</h2>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"profile\">\r\n");
      out.write("        <div class=\"avatar\">A</div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("          <strong>Admin</strong><br>\r\n");
      out.write("          <small>Super Admin</small>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <h1 class=\"section-title\">Overview</h1>\r\n");
      out.write("\r\n");
      out.write("    <!-- STATS -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"stats\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card purple\">\r\n");
      out.write("        <div class=\"icon-box\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("          <h4>TOTAL TEACHERS</h4>\r\n");
      out.write("          <h1>3</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card green\">\r\n");
      out.write("        <div class=\"icon-box\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("          <h4>TOTAL STUDENTS</h4>\r\n");
      out.write("          <h1>4</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card orange\">\r\n");
      out.write("        <div class=\"icon-box\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("          <h4>TOTAL CLASSES</h4>\r\n");
      out.write("          <h1>3</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card red\">\r\n");
      out.write("        <div class=\"icon-box\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("          <h4>AVG ATTENDANCE</h4>\r\n");
      out.write("          <h1>63%</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- TABLES -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"table-wrapper\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"table-card\">\r\n");
      out.write("\r\n");
      out.write("        <h3>Recent Teachers</h3>\r\n");
      out.write("\r\n");
      out.write("        <table>\r\n");
      out.write("          <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th>NAME</th>\r\n");
      out.write("              <th>SUBJECT</th>\r\n");
      out.write("              <th>STATUS</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </thead>\r\n");
      out.write("\r\n");
      out.write("          <tbody>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Ms. Anita Roy</td>\r\n");
      out.write("              <td>English</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Mr. Rajan Mehta</td>\r\n");
      out.write("              <td>Physics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Dr. Priya Sharma</td>\r\n");
      out.write("              <td>Mathematics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Dr. Priya Sharma</td>\r\n");
      out.write("              <td>Mathematics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Dr. Priya Sharma</td>\r\n");
      out.write("              <td>Mathematics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Dr. Priya Sharma</td>\r\n");
      out.write("              <td>Mathematics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Dr. Priya Sharma</td>\r\n");
      out.write("              <td>Mathematics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Dr. Priya Sharma</td>\r\n");
      out.write("              <td>Mathematics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Dr. Priya Sharma</td>\r\n");
      out.write("              <td>Mathematics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Dr. Priya Sharma</td>\r\n");
      out.write("              <td>Mathematics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Dr. Priya Sharma</td>\r\n");
      out.write("              <td>Mathematics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Dr. Priya Sharma</td>\r\n");
      out.write("              <td>Mathematics</td>\r\n");
      out.write("              <td><span class=\"badge active-badge\">Active</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"table-card\">\r\n");
      out.write("\r\n");
      out.write("        <h3>Recent Students</h3>\r\n");
      out.write("\r\n");
      out.write("        <table>\r\n");
      out.write("          <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th>NAME</th>\r\n");
      out.write("              <th>CLASS</th>\r\n");
      out.write("              <th>STATUS</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </thead>\r\n");
      out.write("\r\n");
      out.write("          <tbody>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Sneha Gupta</td>\r\n");
      out.write("              <td>â</td>\r\n");
      out.write("              <td><span class=\"badge enrolled-badge\">Enrolled</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Rohan Singh</td>\r\n");
      out.write("              <td>Grade 10 - B</td>\r\n");
      out.write("              <td><span class=\"badge enrolled-badge\">Enrolled</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Diya Patel</td>\r\n");
      out.write("              <td>Grade 10 - A</td>\r\n");
      out.write("              <td><span class=\"badge enrolled-badge\">Enrolled</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    const toggleBtn = document.getElementById(\"darkToggle\");\r\n");
      out.write("\r\n");
      out.write("    toggleBtn.addEventListener(\"click\", () => {\r\n");
      out.write("      document.body.classList.toggle(\"dark\");\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
