/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-19 11:51:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  <title>School Sidebar</title>\r\n");
      out.write("\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  *{\r\n");
      out.write("  margin:0;\r\n");
      out.write("  padding:0;\r\n");
      out.write("  box-sizing:border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("  font-family:'Poppins',sans-serif;\r\n");
      out.write("  background:#f4f5fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* SIDEBAR */\r\n");
      out.write("\r\n");
      out.write(".schoolSidebar{\r\n");
      out.write("  width:280px;\r\n");
      out.write("  height:100vh;\r\n");
      out.write("  background:#11162d;\r\n");
      out.write("  color:#ffffff;\r\n");
      out.write("  padding:20px 14px;\r\n");
      out.write("  display:flex;\r\n");
      out.write("  flex-direction:column;\r\n");
      out.write("  justify-content:space-between;\r\n");
      out.write("  border-top-right-radius:20px;\r\n");
      out.write("  border-bottom-right-radius:20px;\r\n");
      out.write("  transition:0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* LOGO */\r\n");
      out.write("\r\n");
      out.write(".schoolSidebarLogo{\r\n");
      out.write("  width:48px;\r\n");
      out.write("  height:48px;\r\n");
      out.write("  border-radius:14px;\r\n");
      out.write("  background:#23294b;\r\n");
      out.write("  display:flex;\r\n");
      out.write("  align-items:center;\r\n");
      out.write("  justify-content:center;\r\n");
      out.write("  font-size:24px;\r\n");
      out.write("  margin-bottom:35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* MENU TITLES */\r\n");
      out.write("\r\n");
      out.write(".schoolSidebarMenuTitle{\r\n");
      out.write("  color:#9ca3c7;\r\n");
      out.write("  font-size:12px;\r\n");
      out.write("  letter-spacing:1px;\r\n");
      out.write("  margin:22px 10px 12px;\r\n");
      out.write("  font-weight:600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* MENU */\r\n");
      out.write("\r\n");
      out.write(".schoolSidebarMenuList{\r\n");
      out.write("  list-style:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".schoolSidebarMenuItem{\r\n");
      out.write("  display:flex;\r\n");
      out.write("  align-items:center;\r\n");
      out.write("  gap:14px;\r\n");
      out.write("  padding:14px 16px;\r\n");
      out.write("  border-radius:14px;\r\n");
      out.write("  margin-bottom:10px;\r\n");
      out.write("  color:#b6bdd9;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  transition:0.3s;\r\n");
      out.write("  font-size:15px;\r\n");
      out.write("  font-weight:500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".schoolSidebarMenuItem span{\r\n");
      out.write("  font-size:18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* HOVER */\r\n");
      out.write("\r\n");
      out.write(".schoolSidebarMenuItem:hover{\r\n");
      out.write("  background:#242b4d;\r\n");
      out.write("  color:#ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ACTIVE */\r\n");
      out.write("\r\n");
      out.write(".schoolSidebarActive{\r\n");
      out.write("  background:#4d44cc;\r\n");
      out.write("  color:#ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* DARK MODE */\r\n");
      out.write("\r\n");
      out.write(".schoolSidebarDark{\r\n");
      out.write("  background:#050814;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".schoolSidebarDark .schoolSidebarMenuItem:hover{\r\n");
      out.write("  background:#1c2445;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* RESPONSIVE */\r\n");
      out.write("\r\n");
      out.write("@media(max-width:768px){\r\n");
      out.write("\r\n");
      out.write("  .schoolSidebar{\r\n");
      out.write("    width:100%;\r\n");
      out.write("    height:auto;\r\n");
      out.write("    border-radius:0;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <aside class=\"schoolSidebar\">\r\n");
      out.write("\r\n");
      out.write("    <!-- LOGO -->\r\n");
      out.write("    <div class=\"schoolSidebarTop\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"schoolSidebarLogo\">\r\n");
      out.write("        Rohit\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- MAIN MENU -->\r\n");
      out.write("      <div class=\"schoolSidebarMenuTitle\">\r\n");
      out.write("        MAIN\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"schoolSidebarMenuList\">\r\n");
      out.write("\r\n");
      out.write("        <li class=\"schoolSidebarMenuItem schoolSidebarActive\">\r\n");
      out.write("          <span></span>\r\n");
      out.write("          <a href=\"dashboard.jsp\">Dashboard</a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"schoolSidebarMenuItem\">\r\n");
      out.write("          <span></span>\r\n");
      out.write("          <a href=\"teacher.jsp\">Teacher</a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"schoolSidebarMenuItem\">\r\n");
      out.write("          <span></span>\r\n");
      out.write("          <a href=\"student.jsp\">Students</a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"schoolSidebarMenuItem\">\r\n");
      out.write("          <span></span>\r\n");
      out.write("          <a href=\"classes.jsp\">Classes</a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <!-- ASSIGNMENTS -->\r\n");
      out.write("      <div class=\"schoolSidebarMenuTitle\">\r\n");
      out.write("        ASSIGNMENTS\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"schoolSidebarMenuList\">\r\n");
      out.write("\r\n");
      out.write("        <li class=\"schoolSidebarMenuItem\">\r\n");
      out.write("          <span></span>\r\n");
      out.write("          Assign Students\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"schoolSidebarMenuItem\">\r\n");
      out.write("          <span></span>\r\n");
      out.write("          Assign Teachers\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <!-- ACADEMICS -->\r\n");
      out.write("      <div class=\"schoolSidebarMenuTitle\">\r\n");
      out.write("        ACADEMICS\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"schoolSidebarMenuList\">\r\n");
      out.write("\r\n");
      out.write("        <li class=\"schoolSidebarMenuItem\">\r\n");
      out.write("          <span></span>\r\n");
      out.write("          Attendance\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"schoolSidebarMenuItem\">\r\n");
      out.write("          <span></span>\r\n");
      out.write("          Results\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- BOTTOM -->\r\n");
      out.write("    <div class=\"schoolSidebarBottom\">\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"schoolSidebarMenuList\">\r\n");
      out.write("\r\n");
      out.write("        <li class=\"schoolSidebarMenuItem\">\r\n");
      out.write("          <span></span>\r\n");
      out.write("          Logout\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </aside>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("//ACTIVE MENU\r\n");
      out.write("\r\n");
      out.write("  const schoolSidebarItems = document.querySelectorAll(\".schoolSidebarMenuItem\");\r\n");
      out.write("\r\n");
      out.write("  schoolSidebarItems.forEach(item => {\r\n");
      out.write("\r\n");
      out.write("    item.addEventListener(\"click\", () => {\r\n");
      out.write("\r\n");
      out.write("      schoolSidebarItems.forEach(nav => {\r\n");
      out.write("        nav.classList.remove(\"schoolSidebarActive\");\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      item.classList.add(\"schoolSidebarActive\");\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  // DARK MODE\r\n");
      out.write("\r\n");
      out.write("  const schoolSidebar = document.querySelector(\".schoolSidebar\");\r\n");
      out.write("\r\n");
      out.write("  const schoolSidebarDarkBtn = document.getElementById(\"schoolSidebarDarkBtn\");\r\n");
      out.write("\r\n");
      out.write("  schoolSidebarDarkBtn.addEventListener(\"click\", () => {\r\n");
      out.write("\r\n");
      out.write("    schoolSidebar.classList.toggle(\"schoolSidebarDark\");\r\n");
      out.write("\r\n");
      out.write("  });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
