/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-26 13:36:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.manage_005fclasses;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addclasses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Classes Management UI</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        *{\r\n");
      out.write("            margin:0;\r\n");
      out.write("            padding:0;\r\n");
      out.write("            box-sizing:border-box;\r\n");
      out.write("            font-family:'Poppins',sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            background:#f4f5fb;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: start;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           TOPBAR\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .classPageTopbar{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            padding:12px 28px;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            border-bottom:1px solid #e7e7e7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classPageHeading{\r\n");
      out.write("            font-size:20px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classAdminProfileCard{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            gap:12px;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            padding:10px 14px;\r\n");
      out.write("            border-radius:16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classAdminAvatar{\r\n");
      out.write("            width:42px;\r\n");
      out.write("            height:42px;\r\n");
      out.write("            border-radius:50%;\r\n");
      out.write("            background:linear-gradient(to right,#675cff,#1dd5c8);\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classAdminRole{\r\n");
      out.write("            font-size:13px;\r\n");
      out.write("            color:#8c8c8c;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           PAGE CONTAINER\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .classManagementPageContainer{\r\n");
      out.write("            padding:10px 12px;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classManagementHeaderSection{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            margin-bottom:30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classManagementTitle{\r\n");
      out.write("            font-size:40px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classManagementSubtitle{\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            margin-top:4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           CREATE BUTTON\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .createClassButton{\r\n");
      out.write("            border:none;\r\n");
      out.write("            background:#5c4ef7;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            padding:10px 28px;\r\n");
      out.write("            border-radius:14px;\r\n");
      out.write("            font-size:16px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            transition:0.3s;\r\n");
      out.write("            box-shadow:0 10px 20px rgba(92,78,247,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .createClassButton:hover{\r\n");
      out.write("            background:#4f41f0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classCardsGrid{\r\n");
      out.write("            display:grid;\r\n");
      out.write("            grid-template-columns:repeat(auto-fit,minmax(250px,1fr));\r\n");
      out.write("            gap:20px;\r\n");
      out.write("            overflow-y: scroll;\r\n");
      out.write("            height: 525px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classCardContainer{\r\n");
      out.write("        	width: 271px;\r\n");
      out.write("        	height: 200px;\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:28px;\r\n");
      out.write("            padding:20px;\r\n");
      out.write("            position:relative;\r\n");
      out.write("            overflow:hidden;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classCardTopDecoration{\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            top:0;\r\n");
      out.write("            right:0;\r\n");
      out.write("            width:80px;\r\n");
      out.write("            height:60px;\r\n");
      out.write("            background:#c9c1ff;\r\n");
      out.write("            border-bottom-left-radius:40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classStudentCountBadge{\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            top:24px;\r\n");
      out.write("            right:26px;\r\n");
      out.write("            background:#d8fff6;\r\n");
      out.write("            color:#00bfa5;\r\n");
      out.write("            padding:6px 14px;\r\n");
      out.write("            border-radius:30px;\r\n");
      out.write("            font-size:14px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classCardTitle{\r\n");
      out.write("            font-size:20px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            margin-bottom:4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classCardSectionText{\r\n");
      out.write("            color:#8c8c8c;\r\n");
      out.write("            margin-bottom:20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classCardInfo{\r\n");
      out.write("            margin-bottom:0px;\r\n");
      out.write("            color:#475467;\r\n");
      out.write("            font-size:16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classCardDivider{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:1px;\r\n");
      out.write("            background:#ececec;\r\n");
      out.write("            margin:4px 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classDeleteButton{\r\n");
      out.write("            width:42px;\r\n");
      out.write("            height:42px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:12px;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            font-size:18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           MODAL OVERLAY\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .classModalOverlay{\r\n");
      out.write("            position:fixed;\r\n");
      out.write("            inset:0;\r\n");
      out.write("            background:rgba(0,0,0,0.45);\r\n");
      out.write("            backdrop-filter:blur(6px);\r\n");
      out.write("            display:none;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("            z-index:999;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classModalOverlay.active{\r\n");
      out.write("            display:flex;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           MODAL CONTAINER\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .classModalContainer{\r\n");
      out.write("            width:700px;\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:34px;\r\n");
      out.write("            padding:34px;\r\n");
      out.write("            box-shadow:0 20px 50px rgba(0,0,0,0.18);\r\n");
      out.write("            animation:classPopupAnimation 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes classPopupAnimation{\r\n");
      out.write("\r\n");
      out.write("            from{\r\n");
      out.write("                transform:scale(0.9);\r\n");
      out.write("                opacity:0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            to{\r\n");
      out.write("                transform:scale(1);\r\n");
      out.write("                opacity:1;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           MODAL HEADER\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .classModalHeader{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            margin-bottom:30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classModalTitle{\r\n");
      out.write("            font-size:34px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classCloseModalButton{\r\n");
      out.write("            width:44px;\r\n");
      out.write("            height:44px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:12px;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            font-size:22px;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           FORM GRID\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .classFormGrid{\r\n");
      out.write("            display:grid;\r\n");
      out.write("            grid-template-columns:1fr 1fr;\r\n");
      out.write("            gap:24px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classFormGroup{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            flex-direction:column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classFormLabel{\r\n");
      out.write("            margin-bottom:10px;\r\n");
      out.write("            font-size:15px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            letter-spacing:0.5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classFormInput{\r\n");
      out.write("            height:56px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            outline:none;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            border-radius:14px;\r\n");
      out.write("            padding:0 18px;\r\n");
      out.write("            font-size:17px;\r\n");
      out.write("            border:1px solid #e2e5ef;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           MODAL FOOTER\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .classModalFooter{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:flex-end;\r\n");
      out.write("            gap:18px;\r\n");
      out.write("            margin-top:34px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classCancelButton{\r\n");
      out.write("            border:none;\r\n");
      out.write("            background:#eef1f6;\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            padding:14px 28px;\r\n");
      out.write("            border-radius:14px;\r\n");
      out.write("            font-size:17px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .classSaveButton{\r\n");
      out.write("            border:none;\r\n");
      out.write("            background:#5c4ef7;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            padding:14px 28px;\r\n");
      out.write("            border-radius:14px;\r\n");
      out.write("            font-size:17px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            box-shadow:0 10px 20px rgba(92,78,247,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           RESPONSIVE\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        @media(max-width:768px){\r\n");
      out.write("\r\n");
      out.write("            .classManagementHeaderSection{\r\n");
      out.write("                flex-direction:column;\r\n");
      out.write("                align-items:flex-start;\r\n");
      out.write("                gap:20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .classFormGrid{\r\n");
      out.write("                grid-template-columns:1fr;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .classModalContainer{\r\n");
      out.write("                width:95%;\r\n");
      out.write("                padding:24px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- =========================\r\n");
      out.write("         TOPBAR\r\n");
      out.write("    ========================== -->\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- =========================\r\n");
      out.write("         PAGE CONTENT\r\n");
      out.write("    ========================== -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"classManagementPageContainer\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"classPageTopbar\">\r\n");
      out.write("\r\n");
      out.write("        <h2 class=\"classPageHeading\">\r\n");
      out.write("            Classes\r\n");
      out.write("        </h2>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"classAdminProfileCard\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"classAdminAvatar\">\r\n");
      out.write("                A\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <h4>Admin</h4>\r\n");
      out.write("                <p class=\"classAdminRole\">\r\n");
      out.write("                    Super Admin\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- HEADER -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"classManagementHeaderSection\">\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("\r\n");
      out.write("                <h1 class=\"classManagementTitle\">\r\n");
      out.write("                    Classes\r\n");
      out.write("                </h1>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"classManagementSubtitle\">\r\n");
      out.write("                    Create and manage class rooms\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button \r\n");
      out.write("                class=\"createClassButton\"\r\n");
      out.write("                id=\"openClassModalButton\"\r\n");
      out.write("            >\r\n");
      out.write("                + Create Class\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- CLASS GRID -->\r\n");
      out.write("        <div class=\"classCardsGrid\">\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"classCardContainer\">\r\n");
      out.write("                <div class=\"classCardTopDecoration\"></div>\r\n");
      out.write("                <!-- <div class=\"classStudentCountBadge\">2 students</div> -->\r\n");
      out.write("                <h2 class=\"classCardTitle\">Grade 10 - A</h2>\r\n");
      out.write("                <p class=\"classCardSectionText\">Section A</p>\r\n");
      out.write("                <p class=\"classCardInfo\">Capacity: 40</p>\r\n");
      out.write("                <p class=\"classCardInfo\">Room: 101</p>\r\n");
      out.write("                <div class=\"classCardDivider\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- <div class=\"classCardContainer\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"classCardTopDecoration\"></div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"classStudentCountBadge\">\r\n");
      out.write("                    1 students\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h2 class=\"classCardTitle\">\r\n");
      out.write("                    Grade 10 - B\r\n");
      out.write("                </h2>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"classCardSectionText\">\r\n");
      out.write("                    Section B\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"classCardInfo\">\r\n");
      out.write("                    Capacity: 38\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"classCardInfo\">\r\n");
      out.write("                    Room: 102\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"classCardDivider\"></div>\r\n");
      out.write("\r\n");
      out.write("                <button class=\"classDeleteButton\">\r\n");
      out.write("                    ð\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </div> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- =========================\r\n");
      out.write("         CREATE CLASS MODAL\r\n");
      out.write("    ========================== -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"classModalOverlay\" id=\"classModal\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"classModalContainer\">\r\n");
      out.write("\r\n");
      out.write("            <!-- HEADER -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"classModalHeader\">\r\n");
      out.write("\r\n");
      out.write("                <h2 class=\"classModalTitle\">\r\n");
      out.write("                    Create Class\r\n");
      out.write("                </h2>\r\n");
      out.write("\r\n");
      out.write("                <button \r\n");
      out.write("                    class=\"classCloseModalButton\"\r\n");
      out.write("                    id=\"closeClassModalButton\"\r\n");
      out.write("                >\r\n");
      out.write("                    Ã\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- FORM -->\r\n");
      out.write("\r\n");
      out.write("            <form id=\"addClassForm\">\r\n");
      out.write("                <div class=\"classFormGrid\">\r\n");
      out.write("                    <div class=\"classFormGroup\">\r\n");
      out.write("                        <label class=\"classFormLabel\">CLASS NAME *</label>\r\n");
      out.write("                        <input type=\"text\" id=\"className\" placeholder=\"Grade 10 - A\" class=\"classFormInput\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"classFormGroup\">\r\n");
      out.write("                        <label class=\"classFormLabel\">SECTION</label>\r\n");
      out.write("                        <input type=\"text\" id=\"section\" placeholder=\"A\" class=\"classFormInput\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"classFormGroup\">\r\n");
      out.write("                        <label class=\"classFormLabel\">CAPACITY</label>\r\n");
      out.write("                        <input type=\"number\" id=\"capacity\" placeholder=\"40\" class=\"classFormInput\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"classFormGroup\">\r\n");
      out.write("                        <label class=\"classFormLabel\">ROOM NUMBER</label>\r\n");
      out.write("                        <input type=\"text\" id=\"roomNumber\" placeholder=\"101\" class=\"classFormInput\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"classModalFooter\">\r\n");
      out.write("                    <button type=\"button\" class=\"classCancelButton\" id=\"cancelClassModalButton\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" id=\"createClass\" class=\"classSaveButton\">Create Class</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- =========================\r\n");
      out.write("         JAVASCRIPT\r\n");
      out.write("    ========================== -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"addclasses.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
