/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-23 06:59:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class assignStudent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Assign Students UI</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        *{\r\n");
      out.write("            margin:0;\r\n");
      out.write("            padding:0;\r\n");
      out.write("            box-sizing:border-box;\r\n");
      out.write("            font-family:'Poppins',sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            background:#f4f5fb;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: start;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           TOPBAR\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .assignStudentTopbar{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            padding:12px 28px;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            border-bottom:1px solid #e7e7e7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentTopbarTitle{\r\n");
      out.write("            font-size:20px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentAdminProfile{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            gap:12px;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            padding:10px 14px;\r\n");
      out.write("            border-radius:16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentAdminAvatar{\r\n");
      out.write("            width:42px;\r\n");
      out.write("            height:42px;\r\n");
      out.write("            border-radius:50%;\r\n");
      out.write("            background:linear-gradient(to right,#675cff,#1dd5c8);\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentAdminRole{\r\n");
      out.write("            font-size:13px;\r\n");
      out.write("            color:#8c8c8c;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           PAGE CONTAINER\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .assignStudentPageContainer{\r\n");
      out.write("            padding:15px 12px;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentPageHeading{\r\n");
      out.write("            font-size:40px;\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentPageSubtitle{\r\n");
      out.write("            color:#667085;\r\n");
      out.write("            margin-top:4px;\r\n");
      out.write("            margin-bottom:10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           FORM CARD\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .assignStudentFormCard{\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:30px;\r\n");
      out.write("            padding:10px 20px;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("            margin-bottom:18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentFormGrid{\r\n");
      out.write("            display:grid;\r\n");
      out.write("            grid-template-columns:1fr 1fr;\r\n");
      out.write("            gap:20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentFormGroup{\r\n");
      out.write("            display:flex;\r\n");
      out.write("            flex-direction:column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentFormLabel{\r\n");
      out.write("            margin-bottom:10px;\r\n");
      out.write("            font-size:15px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            color:#5f6b85;\r\n");
      out.write("            letter-spacing:0.5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentSelectInput{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:54px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            outline:none;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            border-radius:14px;\r\n");
      out.write("            padding:0 18px;\r\n");
      out.write("            font-size:17px;\r\n");
      out.write("            border:1px solid #e2e5ef;\r\n");
      out.write("            color:#111827;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           ASSIGN BUTTON\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .assignStudentButton{\r\n");
      out.write("            margin-top:14px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            background:#5c4ef7;\r\n");
      out.write("            color:#ffffff;\r\n");
      out.write("            padding:10px 20px;\r\n");
      out.write("            border-radius:14px;\r\n");
      out.write("            font-size:15px;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            transition:0.3s;\r\n");
      out.write("            box-shadow:0 10px 20px rgba(92,78,247,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentButton:hover{\r\n");
      out.write("            background:#4e40ee;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           TABLE CARD\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .assignStudentTableCard{\r\n");
      out.write("            background:#ffffff;\r\n");
      out.write("            border-radius:30px;\r\n");
      out.write("            overflow-y: scroll;\r\n");
      out.write("            height: 330px;\r\n");
      out.write("            border:1px solid #ececec;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           TABLE\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .assignStudentDataTable{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            border-collapse:collapse;\r\n");
      out.write("            overflow-y: scroll;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentDataTable thead{\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentDataTable th{\r\n");
      out.write("            text-align:left;\r\n");
      out.write("            padding:10px 22px;\r\n");
      out.write("            font-size:13px;\r\n");
      out.write("            color:#98a2b3;\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .assignStudentDataTable td{\r\n");
      out.write("            padding:9px 20px;\r\n");
      out.write("            border-top:1px solid #ececec;\r\n");
      out.write("            font-size:15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           DELETE BUTTON\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        .assignStudentDeleteButton{\r\n");
      out.write("            width:42px;\r\n");
      out.write("            height:42px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:12px;\r\n");
      out.write("            background:#f5f6fb;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            font-size:18px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #fullName{\r\n");
      out.write("        	font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #rollNumber{\r\n");
      out.write("        	display: inline-block;\r\n");
      out.write("    		padding: 7px 14px;\r\n");
      out.write("    		border-radius: 30px;\r\n");
      out.write("    		background: #fff2df;\r\n");
      out.write("    		color: #ff9900;\r\n");
      out.write("    		font-size: 14px;\r\n");
      out.write("    		font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* =========================\r\n");
      out.write("           RESPONSIVE\r\n");
      out.write("        ========================== */\r\n");
      out.write("\r\n");
      out.write("        @media(max-width:768px){\r\n");
      out.write("\r\n");
      out.write("            .assignStudentFormGrid{\r\n");
      out.write("                grid-template-columns:1fr;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .assignStudentDataTable{\r\n");
      out.write("                display:block;\r\n");
      out.write("                overflow-x:auto;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- =========================\r\n");
      out.write("         TOPBAR\r\n");
      out.write("    ========================== -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- =========================\r\n");
      out.write("         PAGE CONTENT\r\n");
      out.write("    ========================== -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"assignStudentPageContainer\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"assignStudentTopbar\">\r\n");
      out.write("\r\n");
      out.write("        <h2 class=\"assignStudentTopbarTitle\">\r\n");
      out.write("            Assign Students\r\n");
      out.write("        </h2>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"assignStudentAdminProfile\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"assignStudentAdminAvatar\">\r\n");
      out.write("                A\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("\r\n");
      out.write("                <h4>Admin</h4>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"assignStudentAdminRole\">\r\n");
      out.write("                    Super Admin\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- PAGE TITLE -->\r\n");
      out.write("\r\n");
      out.write("        <h1 class=\"assignStudentPageHeading\">\r\n");
      out.write("            Assign Students\r\n");
      out.write("        </h1>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"assignStudentPageSubtitle\">\r\n");
      out.write("            Enroll students into classes\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <!-- FORM CARD -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"assignStudentFormCard\">\r\n");
      out.write("        <form action=\"\">\r\n");
      out.write("            <div class=\"assignStudentFormGrid\">\r\n");
      out.write("\r\n");
      out.write("                <!-- STUDENT -->\r\n");
      out.write("                <div class=\"assignStudentFormGroup\">\r\n");
      out.write("                    <label class=\"assignStudentFormLabel\">SELECT STUDENT</label>\r\n");
      out.write("\r\n");
      out.write("                    <select class=\"assignStudentSelectInput\" id=\"studentSelect\">\r\n");
      out.write("                        <option>â Choose â</option>\r\n");
      out.write("                        \r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- CLASS -->\r\n");
      out.write("                <div class=\"assignStudentFormGroup\" >\r\n");
      out.write("                    <label class=\"assignStudentFormLabel\">SELECT CLASS</label>\r\n");
      out.write("\r\n");
      out.write("                    <select class=\"assignStudentSelectInput\" id=\"classSelect\">\r\n");
      out.write("                        <option>â Choose â</option>\r\n");
      out.write("                        \r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- BUTTON -->\r\n");
      out.write("            <button class=\"assignStudentButton\" id=\"assignStudentBtn\">Assign Student</button>\r\n");
      out.write("		</form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- TABLE CARD -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"assignStudentTableCard\">\r\n");
      out.write("\r\n");
      out.write("            <table class=\"assignStudentDataTable\">\r\n");
      out.write("\r\n");
      out.write("                <thead>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <th>#</th>\r\n");
      out.write("                        <th>STUDENT</th>\r\n");
      out.write("                        <th>CLASS</th>\r\n");
      out.write("                        <th>ASSIGNED ON</th>\r\n");
      out.write("                        <th>ROLL NUMBER</th>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                </thead>\r\n");
      out.write("\r\n");
      out.write("                <tbody id=\"enrollmentTableBody\">\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>Aarav Kumar</td>\r\n");
      out.write("                        <td>Grade 10 - A</td>\r\n");
      out.write("                        <td>2024-06-01</td>\r\n");
      out.write("                        <td><button class=\"assignStudentDeleteButton\">ð</button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"assignStudent.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
